### ISSUE TITLE
I cannot unstall Kasaya

### ISSUE THREAD

**Issue by cjslulu** [syscolabs/kasaya#37]
Hello ! I must have made something wrong but I cannot unstall Kasaya (see screenshot). Thank you for your help !
![Error](https://user-images.githubusercontent.com/61505295/75349899-d84d1580-58a5-11ea-806e-816f4ffb7cb2.png)

**Comment by randilu** [comment]
@cjslulu 
Thanks for trying out Kasaya!

Can you please ensure that you have git installed in your machine and it could be accessible globally?

**Comment by mousehunter1121** [comment]
Can you attach the debug.log here?

**Comment by Vira19** [comment]
**Same for me...**


0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'kasaya'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose npm-session 45f699aa35dd94b1
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/kasaya 12ms (from cache)
8 silly pacote tag manifest for kasaya@latest fetched in 26ms
9 timing stage:loadCurrentTree Completed in 38ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule kasaya@0.1.3 checking installable status
17 silly fetchPackageMetaData error for jarvis@github:hliyan/jarvis Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/hliyan/jarvis.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 200 https://registry.npmjs.org/app-root-path 85ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/istanbul-api 83ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/lodash 54ms (from cache)
21 silly pacote range manifest for app-root-path@^2.2.1 fetched in 90ms
22 silly resolveWithNewModule app-root-path@2.2.1 checking installable status
23 silly pacote range manifest for istanbul-api@^2.1.6 fetched in 86ms
24 silly resolveWithNewModule istanbul-api@2.1.6 checking installable status
25 silly pacote range manifest for lodash@^4.17.15 fetched in 59ms
26 silly resolveWithNewModule lodash@4.17.15 checking installable status
27 http fetch GET 200 https://registry.npmjs.org/utill 5ms (from cache)
28 silly pacote range manifest for utill@^0.1.3 fetched in 8ms
29 silly resolveWithNewModule utill@0.1.3 checking installable status
30 http fetch GET 200 https://registry.npmjs.org/xml-formatter 3ms (from cache)
31 silly pacote version manifest for xml-formatter@1.0.1 fetched in 5ms
32 silly resolveWithNewModule xml-formatter@1.0.1 checking installable status
33 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 476ms (from cache)
34 http fetch GET 304 https://registry.npmjs.org/chalk 478ms (from cache)
35 silly pacote range manifest for escape-string-regexp@^2.0.0 fetched in 479ms
36 silly resolveWithNewModule escape-string-regexp@2.0.0 checking installable status
37 silly pacote range manifest for chalk@^2.4.2 fetched in 481ms
38 silly resolveWithNewModule chalk@2.4.2 checking installable status
39 http fetch GET 304 https://registry.npmjs.org/uuid 488ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/xregexp 476ms (from cache)
41 http fetch GET 304 https://registry.npmjs.org/readline 546ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/istanbul-lib-coverage 577ms (from cache)
43 http fetch GET 304 https://registry.npmjs.org/selenium-standalone 500ms (from cache)
44 http fetch GET 304 https://registry.npmjs.org/istanbul-reports 578ms (from cache)
45 http fetch GET 304 https://registry.npmjs.org/axios 583ms (from cache)
46 silly pacote range manifest for uuid@^3.3.2 fetched in 494ms
47 silly resolveWithNewModule uuid@3.4.0 checking installable status
48 silly pacote range manifest for xregexp@^4.2.4 fetched in 482ms
49 silly resolveWithNewModule xregexp@4.3.0 checking installable status
50 silly pacote range manifest for readline@^1.3.0 fetched in 552ms
51 silly resolveWithNewModule readline@1.3.0 checking installable status
52 silly pacote range manifest for istanbul-lib-coverage@^3.0.0 fetched in 583ms
53 silly resolveWithNewModule istanbul-lib-coverage@3.0.0 checking installable status
54 silly pacote range manifest for selenium-standalone@^6.16.0 fetched in 505ms
55 silly resolveWithNewModule selenium-standalone@6.17.0 checking installable status
56 silly pacote range manifest for istanbul-reports@^3.0.0 fetched in 583ms
57 silly resolveWithNewModule istanbul-reports@3.0.0 checking installable status
58 silly pacote range manifest for axios@^0.19.0 fetched in 587ms
59 silly resolveWithNewModule axios@0.19.2 checking installable status
60 http fetch GET 304 https://registry.npmjs.org/webdriverio 496ms (from cache)
61 silly pacote range manifest for webdriverio@^5.8.3 fetched in 500ms
62 silly resolveWithNewModule webdriverio@5.18.7 checking installable status
63 http fetch GET 304 https://registry.npmjs.org/yargs 167ms (from cache)
64 silly pacote range manifest for yargs@^13.3.0 fetched in 169ms
65 silly resolveWithNewModule yargs@13.3.0 checking installable status
66 timing stage:rollbackFailedOptional Completed in 0ms
67 timing stage:runTopLevelLifecycles Completed in 701ms
68 verbose stack Error: spawn git ENOENT
68 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
68 verbose stack     at onErrorNT (internal/child_process.js:469:16)
68 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
69 verbose cwd C:\WINDOWS\system32
70 verbose Windows_NT 10.0.18362
71 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "kasaya"
72 verbose node v12.16.1
73 verbose npm  v6.13.4
74 error code ENOENT
75 error syscall spawn git
76 error path git
77 error errno ENOENT
78 error enoent Error while executing:
78 error enoent undefined ls-remote -h -t ssh://git@github.com/hliyan/jarvis.git
78 error enoent
78 error enoent
78 error enoent spawn git ENOENT
79 error enoent This is related to npm not being able to find a file.
80 verbose exit [ 1, true ]
