### ISSUE TITLE
Installation (postinstall) fails on mac

### ISSUE THREAD

**Issue by kanchankjha** [syscolabs/kasaya#8]
> kasaya@0.1.1 postinstall /usr/local/lib/node_modules/kasaya
> ./scripts/postinstall.js

installing selenium and browser drivers. please wait...
Error while setting up Selenium or Browser driver: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/kasaya/node_modules/selenium-standalone/.selenium'
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! kasaya@0.1.1 postinstall: `./scripts/postinstall.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the kasaya@0.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by AshanthaLahiru** [comment]
@kanchankjha can you try this with root access.

**Comment by kanchankjha** [comment]
root is not there. tried with sudo which fails as well. able to create those directories using sudo manually.

**Comment by kanchankjha** [comment]
this is last few line of debug log:

7148 silly postinstall kasaya@0.1.1
7149 info lifecycle kasaya@0.1.1~postinstall: kasaya@0.1.1
7150 verbose lifecycle kasaya@0.1.1~postinstall: unsafe-perm in lifecycle false
7151 verbose lifecycle kasaya@0.1.1~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/kasaya/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/X11/bin:/usr/local/bin/jamf:/Applications/Wireshark.app/Contents/MacOS
7152 verbose lifecycle kasaya@0.1.1~postinstall: CWD: /usr/local/lib/node_modules/kasaya
7153 silly lifecycle kasaya@0.1.1~postinstall: Args: [ '-c', './scripts/postinstall.js' ]
7154 silly lifecycle kasaya@0.1.1~postinstall: Returned: code: 255  signal: null
7155 info lifecycle kasaya@0.1.1~postinstall: Failed to exec postinstall script
7156 timing action:postinstall Completed in 1243ms
7157 verbose unlock done using /Users/kkumarjh/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
7158 timing stage:rollbackFailedOptional Completed in 634ms
7159 timing stage:runTopLevelLifecycles Completed in 20119ms
7160 verbose stack Error: kasaya@0.1.1 postinstall: `./scripts/postinstall.js`
7160 verbose stack Exit status 255
7160 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
7160 verbose stack     at EventEmitter.emit (events.js:311:20)
7160 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
7160 verbose stack     at ChildProcess.emit (events.js:311:20)
7160 verbose stack     at maybeClose (internal/child_process.js:1021:16)
7160 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
7161 verbose pkgid kasaya@0.1.1
7162 verbose cwd /Users/kkumarjh
7163 verbose Darwin 19.3.0
7164 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "kasaya"
7165 verbose node v12.16.1
7166 verbose npm  v6.13.4
7167 error code ELIFECYCLE
7168 error errno 255
7169 error kasaya@0.1.1 postinstall: `./scripts/postinstall.js`
7169 error Exit status 255
7170 error Failed at the kasaya@0.1.1 postinstall script.
7170 error This is probably not a problem with npm. There is likely additional logging output above.
7171 verbose exit [ 255, true ]

**Comment by poorren** [comment]
Got same error on Windows 10.
===============
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kasaya@0.1.1 postinstall: `./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kasaya@0.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
==============

And I notice there's merge fix for that. Could you push those new fix to npm ? 
I expect to try this new project.

Thanks.

**Comment by randilu** [comment]
We just published a new patch to npm with those fixes. Please try it and let us know if this issue persists.

**Comment by kanchankjha** [comment]
didnt work:

user1@user1-M-R177 ~ % sudo npm install -g kasaya                                      
Password:
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/kasaya -> /usr/local/lib/node_modules/kasaya/kasaya.js

> core-js-pure@3.6.4 postinstall /usr/local/lib/node_modules/kasaya/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> kasaya@0.1.2 postinstall /usr/local/lib/node_modules/kasaya
> scripts/postinstall.js

installing selenium and browser drivers. please wait...
Error while setting up Selenium or Browser driver: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/kasaya/node_modules/selenium-standalone/.selenium'
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! kasaya@0.1.2 postinstall: `scripts/postinstall.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the kasaya@0.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user1/.npm/_logs/2020-02-23T09_56_15_795Z-debug.log
user1@user1-M-R177 ~ %

**created those directories manually**

user1@user1-M-R177 ~ % ls -l /usr/local/lib/node_modules
total 0
drwxr-xr-x  23 root  wheel  736 Feb 18 10:13 npm
user1@user1-M-R177 ~ % sudo mkdir /usr/local/lib/node_modules/kasaya
user1@user1-M-R177 ~ % sudo mkdir /usr/local/lib/node_modules/kasaya/node_modules
user1@user1-M-R177 ~ % sudo mkdir /usr/local/lib/node_modules/kasaya/node_modules/selenium-standalone
user1@user1-M-R177 ~ % sudo mkdir /usr/local/lib/node_modules/kasaya/node_modules/selenium-standalone/.selenium
user1@user1-M-R177 ~ % ls -l /usr/local/lib/node_modules                                                  
total 0
drwxr-xr-x   3 root  wheel   96 Feb 23 15:29 kasaya
drwxr-xr-x  23 root  wheel  736 Feb 18 10:13 npm
user1@user1-M-R177 ~ % 
user1@user1-M-R177 ~ % sudo npm install -g kasaya                                                         
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/kasaya -> /usr/local/lib/node_modules/kasaya/kasaya.js

> core-js-pure@3.6.4 postinstall /usr/local/lib/node_modules/kasaya/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> kasaya@0.1.2 postinstall /usr/local/lib/node_modules/kasaya
> scripts/postinstall.js

installing selenium and browser drivers. please wait...
Error while setting up Selenium or Browser driver: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/kasaya/node_modules/selenium-standalone/.selenium'
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! kasaya@0.1.2 postinstall: `scripts/postinstall.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the kasaya@0.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user1/.npm/_logs/2020-02-23T10_00_27_133Z-debug.log
user1@user1-M-R177 ~ % 


**log file content**

/Users/user1/.npm/_logs/2020-02-23T09_56_15_795Z-debug.log


7153 verbose lifecycle kasaya@0.1.2~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/kasaya/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/X11/bin:/usr/local/bin/jamf:/Applications/Wireshark.app/Contents/MacOS
7154 verbose lifecycle kasaya@0.1.2~postinstall: CWD: /usr/local/lib/node_modules/kasaya
7155 silly lifecycle kasaya@0.1.2~postinstall: Args: [ '-c', 'scripts/postinstall.js' ]
7156 silly lifecycle kasaya@0.1.2~postinstall: Returned: code: 255  signal: null
7157 info lifecycle kasaya@0.1.2~postinstall: Failed to exec postinstall script
7158 timing action:postinstall Completed in 1506ms
7159 verbose unlock done using /Users/user1/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
7160 timing stage:rollbackFailedOptional Completed in 695ms
7161 timing stage:runTopLevelLifecycles Completed in 24973ms
7162 verbose stack Error: kasaya@0.1.2 postinstall: `scripts/postinstall.js`
7162 verbose stack Exit status 255
7162 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
7162 verbose stack     at EventEmitter.emit (events.js:311:20)
7162 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
7162 verbose stack     at ChildProcess.emit (events.js:311:20)
7162 verbose stack     at maybeClose (internal/child_process.js:1021:16)
7162 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
7163 verbose pkgid kasaya@0.1.2
7164 verbose cwd /Users/user1
7165 verbose Darwin 19.3.0
7166 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "kasaya"
7167 verbose node v12.16.1
7168 verbose npm  v6.13.4
7169 error code ELIFECYCLE
7170 error errno 255
7171 error kasaya@0.1.2 postinstall: `scripts/postinstall.js`
7171 error Exit status 255
7172 error Failed at the kasaya@0.1.2 postinstall script.
7172 error This is probably not a problem with npm. There is likely additional logging output above.
7173 verbose exit [ 255, true ]

**Comment by AshanthaLahiru** [comment]
Thanks for hanging with us! This seems not to be an issue with Kasaya. Hope [this](https://hackersandslackers.com/fixing-your-npm-installation) will give you some insights on the issue.

Feel free to reply to this thread if you have any further concerns.
